secrets:
    sops:
        age_key: ENC[AES256_GCM,data:d/MqEQ4vclOO8DEWZEzNd59Eql4KDShfYkslTgLb+4c54UzzVYKySJH6XsVSg/hsN1593uLX91q9RB8qBtiqp4H5IIQ/wcOnTwptjOICv6XyQ99GaPJE10W6K5fTxy/idoRWi4EFEToxF7iHc8mgMI7pyDKdnvhY5NpZwzcFXROw7+KRIYa9RdvcJ0YGhJR3nXah5E8E7zelMl4xJKh8VFO9Gth2gT8YM88klKGwKNdzl2/kP7OzKaPUqH11,iv:aGjP1FHyi9hhgYDU7KWann1fTTeeiYhf16PzTCsASjo=,tag:dSNmx0zcmBkht55aegJC/g==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:+Tfr/RV3fwVekt7v7HImeXC2cY4wiyOGXxDTQrTk23K6r4mr/bMDj3Nz/L9Cg09yw+RJoOqO9EkKPxVvu2OJaPD8Qn3w7vOWNKIDGg==,iv:f3cFW5Gp45+I3cfqNujhPRLsZBLJGhE5J48bABx1pfM=,tag:YS54o95XaLCuETB1Kp+g6A==,type:str]
            username: ENC[AES256_GCM,data:6LuULETrivc=,iv:TSTBctduCRwXo6kS+i+lA9dBSvlVMSqYF1uIBS4KTa8=,tag:YaspZGVDphBHVSSvglmwhg==,type:str]
            password: ENC[AES256_GCM,data:2o/FtlcYcP6XUtFfEd8=,iv:bjxHX2oea7cPbDY7Ks0Uk+m3CEn53mD83izR2OO8E9g=,tag:JXuL774Bev7iO7M2dUBT2A==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:4TPcbDqcd4qP,iv:wEcYKwJO9r019bN6k91WB7tZnllOYP35288JQru7z2E=,tag:HOmkT6VHPOojEppu8/dg/w==,type:str]
                password: ENC[AES256_GCM,data:LXlLvuBzK8OyCRmPXUbopU/QcNLDNu7nf8CYFcXIoPWWrk2ZUCRWQa3wtH99fHmRRexVzz/oPrUnQklHidOPurodM1TQ+C+ZSQp71YGxSZ4nJCBefH4iK3ZSaZhG,iv:iHvJDI+nz0yrP+yr67ke4toDM2d9s18drBOKvSLRZTQ=,tag:UIJdcd0cDeEgfkUiPntctQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz3qsvhwwhu7f794d5lpqkuaw675auq0zph004dc98r3v7n5ac0q82knqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdnM4REhtcHhSS2p6dUVV
            TFVXbTkxUURJWCs4S0lpQmZJdHpGNS90Wm1ZCnpGMUY1Wm1aR250QlRzVTdNMGdm
            TXh0MWpWN241Q3JLNjhveTk5dEhrQ1UKLS0tIHJWRzgrZHlxLy9mbGU2K3pINjYv
            SVFrcmxOWk0vN2F4L2hHRm8wVU54ZFUKbFv+Jsylx2TqsgiWOrLKEiQQPznXb8/t
            DP+VlpToACCHXtFqeu9wOgf/5JSP1/QiuGq7Co0FMXj/IqM1ueJ5bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T11:14:31Z"
    mac: ENC[AES256_GCM,data:uI1FiJ680uLRMP2GIUpRjoLHIzeHjS9IJCecmJtgSTJrU+9QkWa00auWSvfipjfO8TxxoVdqNruU9wgNs9vIHBmL99kcnvONWUJq5wkMH7SYRU3RftrLECJ5kAYwoNOcFAPixJ93ISXpET7v0FtD515OgZY4kqvNM1qr3KtzhEk=,iv:AOM1ZHDCxUGt+byiTWofIMe5M6vLtWYEt56+iCGiwuk=,tag:jW7gVj7asX8N3BLtbzaPwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
