#@ load("validations.star", "valid")

#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
#@schema/title "Tanzu Sync Secrets"
secrets:
  #@schema/title "SoPS Secrets"
  sops:
    #@schema/title "Age Identity"
    #@schema/desc "Age identity/key containing one or more 'recipient'(s) of which at least one must have been named when encrypting sensitive data for this installation."
    #@schema/validation valid.age_key()
    age_key: ""

    #@schema/title "TAP OCI Registry"
    #@schema/desc "Connection information and credentials for the OCI registry hosting TAP PackageRepository."
    registry:
      #@schema/desc "Fully-qualified hostname of OCI registry."
      #@schema/validation min_len=1
      hostname: ""
      #@schema/desc "Username of registry account that has at least read access to the OCI repository containing the TAP PackageRepository."
      #@schema/validation min_len=1
      username: ""
      #@schema/desc "Credential for named registry account."
      #@schema/validation min_len=1
      password: ""

    #@schema/title "Source git repository credentials"
    #@schema/desc "Credentials to the hosted git repository containing the source of truth for the cluster."
    #@schema/validation one_not_null=True
    git:
      #@schema/validation not_null=True, when=lambda _, ctx: not ctx.root["git"]["url"].startswith("https://")
      #@schema/nullable
      ssh:
        #@schema/desc "Private portion of account SSH key or deploy token."
        #@schema/validation min_len=1
        private_key: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEAw947/v7nOOOzMr84WPmlR6cbfiP7l0FihCfU112JAgXvBnlRkw5qsLRuY5mv7Ih3urLbjwjcXy2Os3i3adiij6rFQrIdEHzSeFDnHdCbOETRaz183pbn5+Ez0lBzULRqrkNNE2sQT2So5/LEeNGzyAGFahnnm2hSQrtnAKi1fKJJBLeP8L7Rug6E4E2RFvL90ybpE+WsN1zto++GlpIvx8qjosqRIeZIwkVO8MSj2RAbSyipErbAnCUcuaqE+zq6A0APSyr3dy0Pm8u5CXOyxnuf0oAwR+S2HHpt7DzxDlnnNwKWEVWRogGUacju07naKnHs0XzMxx4rkQed8DQlPNnA1mIDjDY/psuDGqwXkbqbBdH5b88Fd5IkIwrlG/ajLJ5UHBmxag9nSV878qAlC6CqDkKPPYI31RjYfPryt8Eq96icqrc4rfwF0965wHtW53vq38ArGJFMRTG3hdcHQPEcnuePEPwzka5ETp1q8erDvX+XHSpCEShsU6a6sIzvRFUU4KBwxXIKw3QySntq0k/boqNXkpjRjYDDtiF4wpMKDlHbmbHExrpiVEK4EJ/l0axKCBFRfPiodgsVypUXYN01tBBMn3OQVfdJTzWTwZ4+RYIJabqKNBHg4njT8L6cAa9P9QTM/tQ5gM9dBGRZEmTzcb9mau9cPEPACwArE7EAAAdYskMQdLJDEHQAAAAHc3NoLXJzYQAAAgEAw947/v7nOOOzMr84WPmlR6cbfiP7l0FihCfU112JAgXvBnlRkw5qsLRuY5mv7Ih3urLbjwjcXy2Os3i3adiij6rFQrIdEHzSeFDnHdCbOETRaz183pbn5+Ez0lBzULRqrkNNE2sQT2So5/LEeNGzyAGFahnnm2hSQrtnAKi1fKJJBLeP8L7Rug6E4E2RFvL90ybpE+WsN1zto++GlpIvx8qjosqRIeZIwkVO8MSj2RAbSyipErbAnCUcuaqE+zq6A0APSyr3dy0Pm8u5CXOyxnuf0oAwR+S2HHpt7DzxDlnnNwKWEVWRogGUacju07naKnHs0XzMxx4rkQed8DQlPNnA1mIDjDY/psuDGqwXkbqbBdH5b88Fd5IkIwrlG/ajLJ5UHBmxag9nSV878qAlC6CqDkKPPYI31RjYfPryt8Eq96icqrc4rfwF0965wHtW53vq38ArGJFMRTG3hdcHQPEcnuePEPwzka5ETp1q8erDvX+XHSpCEShsU6a6sIzvRFUU4KBwxXIKw3QySntq0k/boqNXkpjRjYDDtiF4wpMKDlHbmbHExrpiVEK4EJ/l0axKCBFRfPiodgsVypUXYN01tBBMn3OQVfdJTzWTwZ4+RYIJabqKNBHg4njT8L6cAa9P9QTM/tQ5gM9dBGRZEmTzcb9mau9cPEPACwArE7EAAAADAQABAAACAQDCgJWjiw2h+Lui0TDraj0vAkrS4Hieo1dpVQSPOVssnyfVjfPrzI02HHbigWOpx3rd828EgxATk/H5Vw8MFQyZDkQFD0q9bLa0s+JOQTFilzQ/AjhV8hUotwH2/90Db6XglwSbG95+eL8iVnm0YMne+2O5ETBlqxrFGcQXa3GN6roH7SELOPKbiH97HovN9k8It8MM9y4lbCqweNN2AoVgKWKF7hJhT4VBJgJWJW9vxgbUg/QhmUl7xX7ZAPQ9ZvwA7kRBqNFFj4HIfG2rbTFC2NDFAHbxbbVKYml2Bq56SdzJS9AqNocAEgGHavl/VzfGnotFHGFd+h/ZTW8RcTbnkThQ81jT1aYUubaHV/+TX3sb8pqNvokrDnozQ/zMqbtSIbDioJ6AKrAQ4Jh76+r97I3yYHBC562MKpY4U8f7BuhM3/kJzTptxX5mALMZu2uSby2uG1SxxOYQJDMMdi5r8L48X1LckbwFF9K4nzFo2J7zi39BtxpaxWvGC2H2CK8dL3f2s4Hgy4ofAxjmzAyM322KVu2xCyyGdyTqgWhD2pArTQcTPUKHjrBULP3wEKEuxx+QPJ09uqkoODRI1bhwEaViolo89+/3+ZNiKwWkh/HRb10q6BNVP6Z6WHoDfAbuHqFgRUtjBqntY1GlHqQHSMVe6+idrsv1fPKAEmYgAQAAAQAad/PH6533wjY3yNBGdIU2+pY1Dcv56a/pC3SPmwAk/ImqSEDp1T0ywv3LmHUSkU+hL6sdjFoDGVOZZoaMgS5opxADlv8NVHMPXspgN9aO++6B6lsfRgwBF53IDJQCCjM9dScXN0u/fjp8kSNy6E1kOD+0ymbe8wNJyw2U36zWhm9A49JT9kqnx3Ho0SvoXN9fPdBbK7KmiR2AhoaTtZ96NdOpyUXxjJ3OLnuS7YameH+HF7nvMG/T/39+K0+b//wC7Yy6bJhHUVzQZj4ZR81JTq6l9GCyvJT3ciPzf54gE8xiocafKtrrPzh1K/Bj7SevNVD3Pky699Vdg8wWrAQhAAABAQDq29CBPKjPktrQkx/8jFja9+5rQ9PFghCKvDhXClM235/unpVP7te5gX6QvCYokCbihLSvb0y9D0kfX1LFV9JazuWKlMYYOf4/J5Bp2WEh+uaAB8Xxv9fPYjQ/Lez7GMv79gmuRgOMj1Dqer3lNxYpb207Sifh8qqqFCCs1dce7dxsZRYJfbYgVZZFPZee9nL+R2fH+IYkfM5uVdl0+7Whw6rkaeLM048feteGt6qpzm5+mAgyBwlVLE4xnpJjTkpNEx4E7u6voLQU2dHA9+TmbSy8MkHkrVNGAfu20GkvIBf/Qp0cFu/4hxfadzEXzGi7dYCNWkfLn2reIRALM9ZBAAABAQDVf+eXKfy9VT2lnL1bxxgmSnYZreX0FlMkVjFjk7mGHN/u+zaZa1YphoWKdT0j4OJCLKen0irkwF6Qc7WT2nfUTJK62U/fxdd7vhal9rSy3iLtmYl8Vj4702ODWFh4AZTm4v+5bhN91PCpQn+v8yBpmD0XsrVQAQkIFwNl/WO5sxaJKHtmbAqDu12oFImuJovExwOMYlJP5kir28bPOCTxMjml08VKP+byAsJy3AASB+gyU+jqOHE3RIHYaNWICXNrc8po527MQYPTWUIcfxnvRYbInX7boOim4UkCEUQROJegUdL9RwjG0EISY1JmqggM0jeeNULMuCzXmgUaI0FxAAAAIXlzZXRoaXlhQHlzZXRoaXlhNE1ENk0udm13YXJlLmNvbQE="
        #@schema/desc "Known hosts entries required to authenticate the remote git repository host."
        #@schema/validation min_len=1
        known_hosts: ""
      #@schema/validation not_null=True, when=lambda _, ctx: ctx.root["git"]["url"].startswith("https://")
      #@schema/nullable
      basic_auth:
        #@schema/desc "Username of account with read permissions to Git repository."
        #@schema/validation min_len=1
        username: ""
        #@schema/desc "Credential for named account."
        #@schema/validation min_len=1
        password: ""
